// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrSuccess-0]
	_ = x[ErrUnknown-100001]
	_ = x[ErrParam-100002]
	_ = x[ErrHttpClient-100003]
	_ = x[ErrTokenInvalid-110001]
}

const (
	_Code_name_0 = "Success"
	_Code_name_1 = "服务异常参数错误HTTP客户端请求错误"
	_Code_name_2 = "Token无效"
)

var (
	_Code_index_1 = [...]uint8{0, 12, 24, 49}
)

func (i Code) String() string {
	switch {
	case i == 0:
		return _Code_name_0
	case 100001 <= i && i <= 100003:
		i -= 100001
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	case i == 110001:
		return _Code_name_2
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
