// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrSuccess-0]
	_ = x[ErrUnknown-100001]
	_ = x[ErrParam-100002]
}

const (
	_Code_name_0 = "Success"
	_Code_name_1 = "服务异常参数错误"
)

var (
	_Code_index_1 = [...]uint8{0, 12, 24}
)

func (i Code) String() string {
	switch {
	case i == 0:
		return _Code_name_0
	case 100001 <= i && i <= 100002:
		i -= 100001
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
