// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	card "yxy-go/internal/handler/card"
	electricity "yxy-go/internal/handler/electricity"
	login "yxy-go/internal/handler/login"
	"yxy-go/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/balance",
				Handler: card.GetCardBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/consumption-records",
				Handler: card.GetCardConsumptionRecordsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/card"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auth",
				Handler: electricity.GetAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recharge-records",
				Handler: electricity.GetElectricityRechargeRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/surplus",
				Handler: electricity.GetElectricitySurplusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/usage-records",
				Handler: electricity.GetElectricityUsageRecordsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/electricity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha-image",
				Handler: login.GetCaptchaImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/code",
				Handler: login.LoginByCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security-token",
				Handler: login.GetSecurityTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: login.SendCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/silent",
				Handler: login.LoginBySilentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/login"),
	)
}
